### ISSUE TITLE
Darker BG

### ISSUE THREAD

**Issue by godalming123** [shaunsingh/nord.nvim#101]
Is it possible to have an option to enable the darker bg in the nord color scheme
**EDIT:**
By darker BG I mean that there is multiple shades of polar night and I think that you are use the second or third shade in the list instead of the darkest this makes it slightky hard to read

**Comment by shaunsingh** [comment]
I'm using the darkest color (#2E3440) for the background and follow what the official documentation recommends. Which text is hard to read? I've followed the original Nord-vim theme pretty closely, but would be happy to adjust colors for better contrast and readability

**Comment by godalming123** [comment]
Maybe it's just a Nord issue since this is the first time I've used that theme. I will try it on vscode.

**Comment by godalming123** [comment]
Can verify that this is the same BG on vscode and that this is a nord style chioce
