### ISSUE TITLE
Manually set highlight colors

### ISSUE THREAD

**Issue by manuelcattelan** [shaunsingh/nord.nvim#107]
Hi @shaunsingh and thanks for your hard work, this colorscheme is lovely!

I was wondering if there's any way to manually change highlight colors. When installed with the default config, the theme comes with a lighter shade of grey as a background color when compared to the README screenshot and I don't really know how to change that.

Thanks in advance and keep up the great work!

**Comment by antoineco** [comment]
@manuelcattelan not the author, but this theme doesn't (yet?) include a helper for overriding highlight groups. Luckily, Vim can do that using `autocmd`, and the method has the advantage to work with any color scheme:

<details>
<summary>
<h4>:page_facing_up: .vimrc (Vim)</h4>
</summary>

```vim
" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_nord
  autocmd!
  " default background
  autocmd ColorScheme nord 
  \       hi Normal  guibg=#1C2434 |
  \       hi NonText guibg=#1C2434
augroup END

colorscheme nord
```

</details>

<details>
<summary>
<h4>:page_facing_up: init.lua (Neovim)</h4>
</summary>

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_nord', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'nord',
  command = -- default background
            'hi Normal  guibg=#1C2434 |' ..
            'hi NonText guibg=#1C2434'
})

vim.cmd'colorscheme nord'
```

</details>

<details>
<summary>
<h4>:art: Result</h4>
</summary>

![image](https://user-images.githubusercontent.com/3299086/188594532-5de67c2c-7b16-4997-b41d-c830524852b3.png)
</details>

---

With that being said, I didn't notice that behaviour myself. I used the color picker on the screenshot, and it does have the same [background color](https://github.com/shaunsingh/nord.nvim/blob/6bfb0f7d6e4faf7cddedd34489efe2d2f586325c/lua/nord/named_colors.lua#L3) as what's defined in the color scheme (see screenshot below).

Could it be that you're running Vim in a terminal that doesn't support 24-bit True Colors, or that you didn't add `set termguicolors` to your Vim config prior to calling `colorscheme nord`?

![image](https://user-images.githubusercontent.com/3299086/188591116-30bfa2a4-c2b7-4c43-a0ad-47c75704070a.png)

**Comment by manuelcattelan** [comment]
@antoineco thanks for the useful info! I'm currently using Kitty (which supports 24-bit true colors) and I did add `set termguicolors`. I'm guessing I just see the colors of my screen (MacBook Air M1) differently from the screenshot provided in the repo's README.

**Comment by manuelcattelan** [comment]
Thanks a lot for the suggestion, will definitely try it!
