### ISSUE TITLE
Invalid character in group name

### ISSUE THREAD

**Issue by wesleyjrz** [shaunsingh/nord.nvim#113]
I've got this error message when I updated to `bf4d094`:

```
                    Error detected while processing nvim_exec() called at /home/wesleyjrz/.config/nvim/plugin/packer_compiled.lua:0:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
```

I rollback and it worked normally.

I'm using NVIM v0.7.0 with Packer.

**Comment by hpb0412** [comment]
I have the same issue. Currently, I am using Neovim 0.7 with Packer.
While waiting for the fix, I set my packer config like this:

```lua
  use({
    "shaunsingh/nord.nvim", -- Colorscheme
    commit = "78f5f001709b5b321a35dcdc44549ef93185e024",
  })
```

The commit hash is from the previous Merge Pull Request
