### ISSUE TITLE
Font in Screenshots

### ISSUE THREAD

**Issue by austinliuigi** [shaunsingh/nord.nvim#119]
Would you mind sharing what font that is in the readme screenshots?

**Comment by code7machine** [comment]
Hi, I dont know if you already found the fonts but the font is called 'Rubik'. At moment I didnt find the nerd font BUT there's 'Inconsolata Nerd Font' which is most similar

**Comment by shaunsingh** [comment]
The font is SFMono

**Comment by code7machine** [comment]
@shaunsingh could you please share the tshighlighting in readme screenshot too?
