### ISSUE TITLE
colorcolumn looks weird

### ISSUE THREAD

**Issue by ikalnytskyi** [shaunsingh/nord.nvim#12]
It seems `colorcolumns` is not supported and showed as two bright blue columns. It think it should be a color that requires less attention.

![image](https://user-images.githubusercontent.com/166626/120523923-2a50e500-c3df-11eb-9e4b-b10d6bebb529.png)

**Comment by shaunsingh** [comment]
Thanks for the reporting the issue. I adjusted the `colocolumn` colors to much darker ones. Can you please update through neovim and test it again when you get the time, let me know if it still looks off 

Sincerely, Shaurya

**Comment by ikalnytskyi** [comment]
It looks much better now, just like in the original `nord-vim`. Thank you!

![image](https://user-images.githubusercontent.com/166626/120613668-1c42a900-c45f-11eb-9c69-5e632ee633c0.png)
