### ISSUE TITLE
Error detected while processing nvim_exec()

### ISSUE THREAD

**Issue by pandasoli** [shaunsingh/nord.nvim#126]
Here is a screenshot
![image](https://user-images.githubusercontent.com/76575902/206827121-1a4f059f-821f-4a11-8518-681e4011f914.png)

And here my `~/.config/nvim/init.vim`
![image](https://user-images.githubusercontent.com/76575902/206827178-a6621f52-cc88-4695-9089-8cba95a8f788.png)

And here is a screenshot I took fast when pressed `q` in the above error
![image](https://user-images.githubusercontent.com/76575902/206827224-25d9909b-8ec6-4e7b-bbbc-c8ac8eb05bae.png)

**Comment by shaunsingh** [comment]
you can try an older commit of the colorscheme 
```
  use({
    "shaunsingh/nord.nvim", -- Colorscheme
    commit = "78f5f001709b5b321a35dcdc44549ef93185e024",
  })
  ```
  
  I'd recommend updating your nvim to atleast `v0.8.0`, in order to work with the new tree-sitter highlights and latest version of the theme

**Comment by Hierosme** [comment]
The PR #132 try to fixe it issue ... could you test it please ?

Regards

**Comment by Hierosme** [comment]
use({
    "shaunsingh/nord.nvim", -- Colorscheme
    commit = "92d53edbc02c129140b5e76f35745d8d35862bec",
  })
