### ISSUE TITLE
IndentBlanklineChar too bright

### ISSUE THREAD

**Issue by kahnc** [shaunsingh/nord.nvim#13]
I would suggest either making this configurable, or changing it to a darker colour like the `nord.comments` colour... the current white is way too bright when you have deeply nested code.

**Comment by shaunsingh** [comment]
Thanks, it should be a simple fix. The comments color would be good

**Comment by shaunsingh** [comment]
Fixed in 

According to the nord docs, nord3_gui was the color they recommended, but I'm open to changing it to something brighter if needed. This is what it looks like right now:

**Comment by kahnc** [comment]
Awesome, this is much better
