### ISSUE TITLE
nord_italic = false not working

### ISSUE THREAD

**Issue by halbedel** [shaunsingh/nord.nvim#138]
The option `vim.g.nord_italic = false` is ignored for me after #137 
If I manually reset to commit 418e2507 the italic settings is woking as expected. 

Thanks for your help.
Really nice theme btw :)

**Comment by Hierosme** [comment]
Hello @emilio ,

any chance you can take a look on it ?

the option ``vim.g.nord_italic = false`` work for you ?

**Comment by emilio** [comment]
Hey, sure, thanks for the ping @Hierosme. It works here and I use it.

@halbedel, are you setting `vim.g.nord_italic = false` _before_ calling `colorscheme nord`?

My PR changed the behavior to check `nord_italic` as soon as the theme is loaded, while before it was checked when `loadSyntax()` was called. If somehow you were setting `nord_italic` after the theme loads but before `loadSyntax()`, then the option might seem to have stopped working.

The fix in that case is to set `vim.g.nord_italic = false` earlier in your vim config.

**Comment by Hierosme** [comment]
It afternoon i have chaeck and:

Now with @emilio PR #137 the logic about italic and bold is on the top of the theme.lua file, and the entire theme use  that logic resuslt by variables.

Work well for me too.

Could you explain how you load the theme @halbedel ? (pure lua , vimscript, both ...)

**Comment by halbedel** [comment]
Thanks, my configuration is working now. Just had to move the `colorscheme nord` all the way to the end :)

```lua
-- set colorscheme with protected call in case it isn't installed
local status, nord = pcall(require, "nord")
if not status then
	print("Colorscheme not found!") -- print error if colorscheme not installed
	return
end

vim.g.nord_disable_background = true
vim.g.nord_italic = false

nord.set()

vim.cmd([[colorscheme nord]])

```
