### ISSUE TITLE
Having Trouble

### ISSUE THREAD

**Issue by ocelotStride** [shaunsingh/nord.nvim#139]
I downloaded the theme using Packer. I add vim.cmd[[colorscheme nord]] to my init.lua. Unfortunately I end up with all of my text grey after doing this.

I'm doing this in terminal.app on macOS and I currently have the Nord theme setup for the terminal. Is there a conflict here that I'm missing?

**Comment by shaunsingh** [comment]
I believe `terminal.app` doesn't support termguicolors/truecolor (which is required for this theme). You'd have better luck with `iterm2` or another supported terminal emulator

**Comment by ocelotStride** [comment]
I see, thank you
