### ISSUE TITLE
ColorColumn foreground color

### ISSUE THREAD

**Issue by delafthi** [shaunsingh/nord.nvim#19]
First of all, thank you for this theme. 

I was wondering why the foreground color of `ColorColumn` is set to `nord.nord0_gui` instead of `nord.none`? In my opinion it would make more sense to leave the text color as it is. The following image shows a file using markdown syntax with the current foreground color.
![colorcolumn_fg](https://user-images.githubusercontent.com/50531499/124511150-b9ce2700-ddd5-11eb-96c7-067f02147a4d.jpg)

**Comment by shaunsingh** [comment]
> I was wondering why the foreground color of ColorColumn is set to nord.nord0_gui instead of nord.none?

I never used color column before, so I just never noticed it. Thanks for pointing it out, its fixed now!

Fixed in https://github.com/shaunsingh/nord.nvim/commit/f576bea507648be342336f7a3f08b5e561792292
