### ISSUE TITLE
Disable italics?

### ISSUE THREAD

**Issue by thallium** [shaunsingh/nord.nvim#27]
Is there an option to disable italics?

**Comment by shaunsingh** [comment]
Soon, I dislike italics as well.

**Comment by shaunsingh** [comment]
Added in https://github.com/shaunsingh/nord.nvim/commit/771fc22e458a9bf7a28134acf038663fcb12de6b

Lmk if it works for you. Some ui features (e.g. folds) still use italics, but it will be disabled for all syntax
