### ISSUE TITLE
Having issues with installing nord.nvim

### ISSUE THREAD

**Issue by PhantomRex123** [shaunsingh/nord.nvim#28]
Here is the error i get

```
Error detected while processing /home/ryan/.config/nvim/plugged/nord.nvim/colors/nord.vim:
line    9:
E5105: Error while calling lua chunk: .../ryan/.config/nvim/plugged/nord.nvim/lua/nord/colors.lua:44: attempt to index field 'g' (a nil value)
```

And then here is my init.vim

```
call plug#begin()
Plug 'sheerun/vim-polyglot'
Plug 'ryanoasis/vim-devicons'
Plug 'preservim/nerdtree'
Plug 'pearofducks/ansible-vim'
Plug 'Yggdroot/indentLine'
Plug 'itchyny/lightline.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'shaunsingh/nord.nvim'
call plug#end()

colorscheme nord
```

**Comment by shaunsingh** [comment]
By any chance were you using an older version of the configuration I posted on the `README`? I recently changed the vimscript configuration instructions

**Comment by 9ebd7134** [comment]
> By any chance were you using an older version of the configuration I posted on the `README`? I recently changed the vimscript configuration instructions

I installed this yesterday , so i guess no?

**Comment by musicaljoeker** [comment]
I am also having this issue with a very similar error message. I'm not a Lua developer, but it seems like something in the `vim.g` array reference is going awry.

**Comment by 9ebd7134** [comment]
> I am also having this issue with a very similar error message with a fresh installation. I'm not a Lua developer, but it seems like something in the `vim.g` array reference is going awry.

I have found a way to fix this issue, `init.vim`
```vimscript
call plug#begin()
  Plug 'arcticicestudio/nord-vim', { 'branch': 'develop', 'on':  'NERDTreeToggle' }
call plug#end()

" Set the color scheme
colorscheme nord
```

Run :PlugInstall and it should work :)

**Comment by shaunsingh** [comment]
> I have found a way to fix this issue, init.vim

Looks like thats `nord-vim`, not `nord.nvim`.

Could you guys try setting all the settings at the bottom? I imagine I messed something up with vim.g. and the options when I was refactoring two days back

**Comment by bjanaszek** [comment]
I've tried the sample vimscript configuration, and am still seeing the error.  I just installed the plugin today.

**Comment by 9ebd7134** [comment]
Ok! So i fixed this error by installing the 'Nightly version' of neovim :)

**Comment by 9ebd7134** [comment]
Here is an image : 
Latest stable version of neovim

![Screenshot from 2021-08-06 23-04-34](https://user-images.githubusercontent.com/78041469/128556606-d7c535fa-ffa7-4b68-8c4b-d538932cdec7.png)
Nightly version

![Screenshot from 2021-08-06 23-05-20](https://user-images.githubusercontent.com/78041469/128556610-7dab0073-d1c2-45d9-b24f-d344e0243e37.png)

**Comment by shaunsingh** [comment]
Thanks, I previously tested it with 0.5 stable but something might've changed within the last few commits 

The stable verion you are using is neovim 0.5.0 correct? I'm targeting 0.5.0 stable minimum

Additionally. what OS is that and how did you install neovim? Looks like macOS but I'm not sure if it is

**Comment by 9ebd7134** [comment]
I haven't tested it on 5.0 , the thing is `sudo apt install neovim` installs v4.3 which doesn't fully support new commits added. https://www.reddit.com/r/neovim/comments/fyemoh/how_can_i_update_my_neovim/

**Comment by shaunsingh** [comment]
I can't really support 0.4.x neovim because it just lacks lua features that the theme needs to function sorry. As someone in that thread said, you can use the app image. 

You can also use the ppa via 

```
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
```

Or install another package manager alongside apt such as `nix`

@musicaljoeker @bjanaszek can you try the fixes above as well?
