### ISSUE TITLE
Any support for vim-signify?

### ISSUE THREAD

**Issue by cd-rum** [shaunsingh/nord.nvim#29]
These colors appear to be inverted:

<img width="73" alt="image" src="https://user-images.githubusercontent.com/12165422/127798033-3739e903-a954-4db4-9ccf-0bb32d126d41.png">

Any way to switch the background and the `!`?

**Comment by shaunsingh** [comment]
I don't have plans to support vim-signify, but I do support [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim), a lua based alternative!

**Comment by cd-rum** [comment]
Amazing, thanks so much@
