### ISSUE TITLE
could not override BufferLineFill

### ISSUE THREAD

**Issue by xiehuc** [shaunsingh/nord.nvim#30]
![截屏2021-08-03 下午5 23 39](https://user-images.githubusercontent.com/571878/127991918-9f75b5f6-0d85-4dd6-be0a-b36bee022245.png)

because nord async set BufferLineFill, it is ugly

and i could not find a way override it, because it is asynced

**Comment by shaunsingh** [comment]
1. Would you prefer if I move it to the main (non asynced) loop? 
2. What color would you prefer it?

**Comment by xiehuc** [comment]
I have no idea,

maybe there are two solution
1. add a config flag to enable/disable this line
2. move it to main also ok, because this just set two highlight, doesn't slow at all.

I think BufferLine default color is ok, because it generate from current colorscheme

**Comment by shaunsingh** [comment]
Thanks, could you updated the theme and try it out again? I think it should be fixed in https://github.com/shaunsingh/nord.nvim/commit/74a3998ad646b442600db9eabe167edcdd3341d3

**Comment by xiehuc** [comment]
```
require("bufferline").setup {
  options = {
    separator_style = "slant"
  },
  highlights = {
    fill = {guibg = "#FF0000"}
  }
}

```

![截屏2021-08-03 下午9 32 12](https://user-images.githubusercontent.com/571878/128024199-c5f8dd3e-043e-45c6-a5de-70022de5e531.png)

i test, it can set color now, 

![截屏2021-08-03 下午9 36 07](https://user-images.githubusercontent.com/571878/128024806-03e61286-c820-4105-8962-477866cffb64.png)

and default color is also ok.


also, i think `BufferLineFill =              { bg = nord.bg },` would never effective, what ever i put load command before or after bufferline setup. and i don't know why.

**Comment by xiehuc** [comment]
thank you very much
