### ISSUE TITLE
Issues with colorscheme

### ISSUE THREAD

**Issue by stasjok** [shaunsingh/nord.nvim#32]
1. `nord_italic` option doesn't work properly.
   - Looks like logic is inverted (need to set it to false in order to enable italics): https://github.com/shaunsingh/nord.nvim/blob/5cb83dfa9158512ead196e449b86eab952a17931/lua/nord/theme.lua#L54-L70
   - Treesitter highlights doesn't use it, so it doesn't work at all if treesitter is enabled: https://github.com/shaunsingh/nord.nvim/blob/5cb83dfa9158512ead196e449b86eab952a17931/lua/nord/theme.lua#L198
   - Is it possible to enable italics only for comments?
2. LSP highlights are white on white: https://github.com/shaunsingh/nord.nvim/blob/5cb83dfa9158512ead196e449b86eab952a17931/lua/nord/theme.lua#L281-L283
3. Same for `NeogitHunkHeader`: https://github.com/shaunsingh/nord.nvim/blob/5cb83dfa9158512ead196e449b86eab952a17931/lua/nord/theme.lua#L313
4. I think there is pretty poor choice for search highlights. For example IncSearch is highlighted with white. If text is already white, then it's unreadable. And even regular search-highlight changes text color to white with slight background. Usually it's the opposite, highlighted text has prominent background color instead of erasing syntax highlighting. Maybe `style = 'reverse'` shouldn't be used there?
Normal color:
![Screenshot 2021-08-09 165722](https://user-images.githubusercontent.com/1353637/128718211-9af3a6db-f957-4765-a380-37814e9517f8.png)
Search highlight for `nor`:
![Screenshot 2021-08-09 165620](https://user-images.githubusercontent.com/1353637/128718251-2e675722-f4fa-419f-b0ee-20bfed877722.png)
5. Also I'd like to point out that "async" is pretty useless here: https://github.com/shaunsingh/nord.nvim/blob/5cb83dfa9158512ead196e449b86eab952a17931/lua/nord/util.lua#L47
It doesn't improve startuptime at all. It just delays execution of a function to some later time, but you still can't use neovim until it's done. You can try to add `os.execute("sleep 10")` anywhere in your async function, than run neovim. You'll see, that neovim isn't responding for 10 seconds after startup. So this async just complicates code, trick profiler, but doesn't improve loading time.

**Comment by shaunsingh** [comment]
1. I'll reverse the logic, thank you. I'll have it adjust treesitter highlights as well. I can also add a seperate option only for comments (e.g. *nord_italic_comments*)
2. Thanks, I don't use lsp/neogit much so what colors would you prefer these be?
3. see above
4. I personally quite like the search colors, something harsher for the word you're on and more subtle colors for words around it. I'll see what the original theme does though, maybe I can improve it 

5. I've been wondering about this as well. I already removed async from my private configuration, I'm just profiling a bit more so I can verify that it doesn't make a difference in performance before I can push changes. The main colors (those required for boot, treesitter, syntax, dashboard, etc) are already loaded without async, so if nord.nvim is loaded properly (i.e. lazied on ColorschemePre) it shouldn't technically block neovim. I'll think about this one a little more

**Comment by vshalt** [comment]
Keeping the cursor on a word for about 3 seconds makes the word unreadable (white foreground and background). Something similar to the 4th point in the comment by @stasjok

**Comment by shaunsingh** [comment]
Issues 1, 2, 3 should be fixed now. Working on 4 and 5 

@vshalt I assume you're using that plugin that highlights other references of the word under the cursor? (the name is escaping me)

**Comment by shaunsingh** [comment]
The plugin was vim-illuminate, that issue should be fixed now.

**Comment by shaunsingh** [comment]
issue 4 is fixed as well. The original (nord-vim) theme uses white for the fg and an artic-blue for the bg, so I just stuck with those

**Comment by shaunsingh** [comment]
Lmk if you need anything else, someone said they were going to pr with a fix for 5 and a few other improvements soon, so I’m waiting on that
