### ISSUE TITLE
error while using nord

### ISSUE THREAD

**Issue by WyeneDev** [shaunsingh/nord.nvim#33]
Error detected while processing /home/wyene/.vim/plugged/nord.nvim/colors/nord.vim:
line    1:
E319: Sorry, the command is not available in this version: lua << EOF
line    2:
E492: Not an editor command: package.loaded['nord'] = nil
line    3:
E492: Not an editor command: package.loaded['nord.util'] = nil
line    4:
E492: Not an editor command: package.loaded['nord.colors'] = nil
line    5:
E492: Not an editor command: package.loaded['nord.theme'] = nil
line    6:
E492: Not an editor command: package.loaded['nord.functions'] = nil
line    8:
E492: Not an editor command: require('nord').set()
line    9:
E492: Not an editor command: EOF

**Comment by SilverRainZ** [comment]
This colorschema is for neovim, not vim.

**Comment by shaunsingh** [comment]
Yup, you need a neovim version 0.5 or higher, since the theme uses Lua
