### ISSUE TITLE
When using `require('nord').set()` the set function is called twice

### ISSUE THREAD

**Issue by ryantking** [shaunsingh/nord.nvim#35]
I was trying to customize a few highlight groups in the packer config function by doing something like this:
```lua
config = function()
    require('nord').set()
    local util = require('nord.util')
    local colors = require('nord.colors')
    util.highlight('WhichKey', {bg = colors.nord_gui0})
end
```

And noticed that highlights weren't sticking. Via the power of print statements I determined that after the config function, the ret function was being called a second time via:
https://github.com/shaunsingh/nord.nvim/blob/296167d2625e478d90f711bc8c0f2be96533b311/colors/nord.vim#L8

I got my highlights working by doing them in a separate module, but I figured that this was probably not desired behavior? Could also be a user error.

**Comment by shaunsingh** [comment]
I'm not very familiar with loading things like this via packer. I assume the fix should be to remove that line?

**Comment by ryantking** [comment]
So I think the issue is that the `colors/nord.nvim` is loaded whenever the theme is set so you could get rid of the line, but that would break users using the theme the traditional `colorscheme nord` way. I'm going to peek at some other neovim colorschemes and see what they do. One idea is using a bool that gets set to true on the first set call to prevent subsequent calls?

Another issue I found was that with the plugin highlights being done async, they are overwriting my manual highlight statements done elsewhere in my config. What I'm doing in my fork is accepting highlight overrides as an argument to set. Would you be interested in getting that cleaned up and PRed in? Again I'll look at some other lua themes and see what patterns they use.

**Comment by shaunsingh** [comment]
>  One idea is using a bool that gets set to true on the first set call to prevent subsequent calls?

It sounds a  bit hacky, I think tokyonight handles this case so I'll look into it 

> What I'm doing in my fork is accepting highlight overrides as an argument to set. Would you be interested in getting that cleaned up and PRed in? Again I'll look at some other lua themes and see what patterns they use.

I was actually looking to get rid of async alltogether, since it doesn't actually speed up anything and rather creates more problems.

**Comment by ryantking** [comment]
It looks like Tokyonight just doesn't tell you to directly call it's set function, rather use the `colorscheme` command, which will in turn call the set function.

So it looks like updating the README to suggest using `colorscheme nord` will resolve the extra set call issue and then removing the asynchronous stuff will stop the user highlights from being overridden. I'm going to do both in my fork, let me know if you'd like me to PR it versus doing it yourself or something else entirely.

**Comment by shaunsingh** [comment]
I would prefer a PR if possible, I'm just swamped with work today. 

Thanks for all the help!
