### ISSUE TITLE
Nvim-tree symlinked directories too dark

### ISSUE THREAD

**Issue by d-miketa** [shaunsingh/nord.nvim#36]
Hi,

Really enjoying the collection of themes! Any chance you could increase the contrast on symlinked directories in `nvim-tree`?
<img width="212" alt="image" src="https://user-images.githubusercontent.com/320321/129491926-a034cfc3-9f75-4c9d-b8e2-4aa99ed34dc7.png">

Thanks!

**Comment by shaunsingh** [comment]
Hi, I'm might've forgot to set this highlight, I'll take a look

**Comment by d-miketa** [comment]
Hey, I don't think you forgot to set anything; separate treatment of symlinked and empty folders is just not offered by Nvim-tree. I opened a feature request some time ago (and forgot about it!): https://github.com/kyazdani42/nvim-tree.lua/issues/504

I'd still like to override that highlight group, at least locally, but the async loading of plugin themes seems to be interfering with that plan. Would you consider adding a way to tinker with specific highlight groups, perhaps by merging default and user-defined colour assignments?

**Comment by d-miketa** [comment]
Or perhaps I'm doing something wrong, since Folded doesn't change either despite synchronous loading (in the editor group)?

Here's what I have in Packer. The `config.colours` module is set up after yours. Manually running `:lua require'config.colours'.set()<CR>` correctly sets all custom highlights.
```
        use {'shaunsingh/nord.nvim',
            config = function()
                require'nord'.set()
                require'config.colours'.set()
            end
        }
```

**Comment by shaunsingh** [comment]
> I'd still like to override that highlight group, at least locally, but the async loading of plugin themes seems to be interfering with that plan. Would you consider adding a way to tinker with specific highlight groups, perhaps by merging default and user-defined colour assignments?

By the end of today I'm removing the async thing, since its causing more trouble without a noticible performance gain. After that you should be able to set the highlight groups as you usualy would

**Comment by d-miketa** [comment]
Thanks – works great now! :)

**Comment by shaunsingh** [comment]
No problem! Feel free to to open another issue (or reopen this one) once the highlight gets added to NvimTree.
