### ISSUE TITLE
Folds are way too dark

### ISSUE THREAD

**Issue by d-miketa** [shaunsingh/nord.nvim#37]
Hey, I think folds would benefit from more contrast:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/320321/130107366-e92999ba-89d0-47bc-aa05-08d7a49d427a.png">

**Comment by shaunsingh** [comment]
Sure, I personally like the subdued color, but I'll see what nord-vim uses

**Comment by shaunsingh** [comment]
Fixed in https://github.com/shaunsingh/nord.nvim/blob/master/lua/nord/theme.lua, uses comment color and matches original nord-vim theme
