### ISSUE TITLE
Syntax highlighting not working with treesitter!

### ISSUE THREAD

**Issue by PhantomRex123** [shaunsingh/nord.nvim#39]
Image: 
![Screenshot from 2021-08-23 16-33-32](https://user-images.githubusercontent.com/78041469/130444126-fc1cb7ff-2070-4538-b4ac-0a10d826ab9a.png)

Issue: No syntax highlighting for cpp ?

Code : 
```
lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = {"c", "cpp", "css", "scss", "html", "javascript", "typescript", "json", "vim"}, 
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false
  },
}
EOF
```

**Comment by reisnobre** [comment]
I think it's working, it just doesn't have enough contrast.

**Comment by shaunsingh** [comment]
Yup, I can't really change the colors the parser uses sorry. Similar issue with .toml files, maybe open an issue in the treesitter repo
