### ISSUE TITLE
Issue with HTML documents

### ISSUE THREAD

**Issue by hackorum** [shaunsingh/nord.nvim#41]
![issue](https://user-images.githubusercontent.com/70092545/131240556-48c173df-3c63-474a-af8c-920af42de9f4.gif)
This only happens when using treesitter. Otherwise it works fine.

**Comment by hackorum** [comment]
nvm i fixed it.

**Comment by shaunsingh** [comment]
How did you fix it btw? Same thing happens with me on latex documents, but it isn’t a colorscheme issue

**Comment by hackorum** [comment]
I thought i fixed it but it still there. It was gone because I forgot to source the treesitter file.

**Comment by hackorum** [comment]
There is a related patch: https://github.com/nvim-treesitter/nvim-treesitter/issues/1702. But I don't know how to apply it.

**Comment by hackorum** [comment]
I tried it once again and it is not there anymore. I did not do anything to fix it but it automagically got fixed.
