### ISSUE TITLE
Indent Blankline show_current_context not working

### ISSUE THREAD

**Issue by hackorum** [shaunsingh/nord.nvim#44]
https://user-images.githubusercontent.com/70092545/131962416-9e9ef13d-8630-4491-9d8b-74ac656b07b8.mov

**Comment by shaunsingh** [comment]
Looks like I made both the context and regular colors the same by accident, sorry! Fixed in https://github.com/shaunsingh/nord.nvim/commit/34e9189d223d823ec27942926362ef4237e3345b, I'm using a dark-ish blue color for now. Lmk if you prefer a different color!
