### ISSUE TITLE
Adding transparent background also makes the sidebar transparent

### ISSUE THREAD

**Issue by Shivansh-007** [shaunsingh/nord.nvim#5]
### Expected Behaviour
It should just make the editor panel transparent but not the explorer

This is an example, folke's tokyonight theme

![image](https://user-images.githubusercontent.com/69356296/118587165-b9dc7e00-b7b9-11eb-9f7c-35587c5f8e7a.png)

### Actual Behaviour
It makes both the editor panel and the explorer panel transparent

![Screenshot from 2021-05-18 09-17-47](https://user-images.githubusercontent.com/69356296/118587277-f4deb180-b7b9-11eb-82de-78140ac52414.png)

**Comment by Shivansh-007** [comment]
That would be awesome, thankyou!

**Comment by Shivansh-007** [comment]
Any updates on this @shaunsingh?

**Comment by shaunsingh** [comment]
@Shivansh-007 Sorry for the delay! Work was quite busy the past month and I didn't have much time. I'll try to get a fix in by the end of the week

**Comment by Shivansh-007** [comment]
Perfect! Sounds good!

**Comment by shaunsingh** [comment]
Fixed in https://github.com/shaunsingh/nord.nvim/commit/ce8152c9998658b9d739aa880b61c16f3a17385c, Sorry I couldn't get it done earlier.
