### ISSUE TITLE
Neovim HEAD changed LSP highlight groups

### ISSUE THREAD

**Issue by d-miketa** [shaunsingh/nord.nvim#51]
A recent change  https://github.com/neovim/neovim/pull/15585 replaced LSP diagnostic highlight groups, see https://github.com/neovim/neovim/issues/14090#issuecomment-921312955.

**Comment by shaunsingh** [comment]
Looks like 0.5.1 just got released so that means I don't have to target two different versions
I have a fix ready to go for this, just waiting a day or two for package managers to get caught up before pushing it

**Comment by shaunsingh** [comment]
Even better, I just linked the two for now. In the future I'll clean it up
