### ISSUE TITLE
doc/tags is committed to the repo

### ISSUE THREAD

**Issue by jdhao** [shaunsingh/nord.nvim#52]
Please do not commit the file `doc/tags` to the repo, the tags files will be generated automatically by nvim if `helptags` is run.

**Comment by shaunsingh** [comment]
Ah, thanks for that. I will fix this soon along with some other updates

**Comment by shaunsingh** [comment]
Is doc/tags.txt supposed to be not committed as well? or just doc/tags

**Comment by jdhao** [comment]
The two files are not supposed to be committed. You only need to commit the file doc/nord.txt.
