### ISSUE TITLE
feat: styles for romgrk/barbar.nvim

### ISSUE THREAD

**Issue by aserowy** [shaunsingh/nord.nvim#6]
Hi,

can you add styles for romgrk/barbar.nvim? Or can you give me a hint, where i can get and add stylings for bufferlines? (I could pr you then).

Kind regards, Alexander

**Comment by shaunsingh** [comment]
Hi, thank you for your interest in the theme, this was something I was looking into as well. Personally I would like to switch the background and foreground color for the buffer line (right now its light grey in the back and bg in the front) 

According to barber, these are the highlight groups used:
``` 
let fg_target = 'red'

let fg_current  = s:fg(['Normal'], '#efefef')
let fg_visible  = s:fg(['TabLineSel'], '#efefef')
let fg_inactive = s:fg(['TabLineFill'], '#888888')

let fg_modified  = s:fg(['WarningMsg'], '#E5AB0E')
let fg_special  = s:fg(['Special'], '#599eff')
let fg_subtle  = s:fg(['NonText', 'Comment'], '#555555')

let bg_current  = s:bg(['Normal'], '#000000')
let bg_visible  = s:bg(['TabLineSel', 'Normal'], '#000000')
let bg_inactive = s:bg(['TabLineFill', 'StatusLine'], '#000000')
```

Those highlight groups are already described in  [theme.lua](https://github.com/shaunsingh/nord.nvim/blob/master/lua/nord/theme.lua), with the names of  `Normal, TabLineSel, TabLineFil, WarningMsg, Special, and NonText.`

Messing around with those hex colors, specifically TabLineSel and TabLineFill, should fix the issue. Let me know if you need anything else

**Comment by shaunsingh** [comment]
looks like the variables I mentioned only take care of forground/text colors. I'm not sure how to integrated background colors yet

**Comment by shaunsingh** [comment]
Hi! I've been working on highlighting for `nvim-bufferline`, an alternative to barbar. I expect the changes to be done and merged by the end of the week

**Comment by aserowy** [comment]
cool, give me a hint when you are finished. thus, i can look into it.

Kind regards

**Comment by shaunsingh** [comment]
After a bit of testing this is what I came up with 
```lua
local bg = "#2e3440"
local bg2 = "#3b4252"
local bg3 = "#282c34"
local fg = "#CACed6"
local accent = "#81a1c1"
local accent2 = "#BF616A" -- Not saved
local accent3 = "#EBCB8B" -- Not saved
 require('bufferline').setup {
    highlights = {
         fill = {
             guibg = bg
         },
        background = {
            guibg = bg
        },

        -- buffer
        buffer_selected = {
            guifg = fg,
            guibg = bg2,
            gui = "bold"
        },
        separator = {
            guifg = bg3,
            guibg = bg
        },
        separator_selected = {
            guifg = bg3,
            guibg = bg2
        },
        separator_visible = {
            guifg = bg2,
            guibg = bg2
        },
        indicator_selected = {
            guifg = accent,
            guibg = bg2
        },

        -- tabs over right
        tab = {
            guifg = fg,
            guibg = bg
        },
         tab_selected = {
            guifg = accent,
            guibg = bg2
        },
         tab_close = {
            guifg = accent,
            guibg = bg2
        },
        modified_selected = {
            guifg = accent2,
            guibg = bg2
        },
        modified = {
            guifg = accent3,
            guibg = bg
        },
        modified_visible = {
            guifg = accent,
            guibg = bg
        }
    }
}
```

**Comment by g-e-o-m-e-t-r-i-c** [comment]
![image](https://user-images.githubusercontent.com/79387351/147802486-4f7b7c14-4d51-4f6d-a566-3abc93111bdf.png)
would it be possible to add support for the buffer picking function in barbar? appreciate if the color for buffer pick fitted with the overall colorscheme.
