### ISSUE TITLE
Should the highlight of the search be more obvious?

### ISSUE THREAD

**Issue by Yogaflre** [shaunsingh/nord.nvim#66]
<img width="505" alt="Screen Shot 2021-11-24 at 11 34 18" src="https://user-images.githubusercontent.com/30015067/143170263-e030ab25-f2dd-47be-ad0a-0c87f7bfa61f.png">

Modifying the background color may be a better choice.

**Comment by shaunsingh** [comment]
That was more of an opinionated choice. I'll try it out for a while and see if I like the new color
