### ISSUE TITLE
colors are washed

### ISSUE THREAD

**Issue by aserowy** [shaunsingh/nord.nvim#7]
Hi,

me again :) after filing the feature request, i saw the intro picture again while my nvim was open.
Now it bugs me, that my colors are not that strong like yours and i don't see why

![image](https://user-images.githubusercontent.com/8199164/118629756-311c0d00-b7ce-11eb-9acb-7300607cf2fc.png)

Do you have any idea what the cause can be?

Kind regards, Alexander

**Comment by aserowy** [comment]
Got it... it is the font weight.

Sry for the inconvenience.

**Comment by shaunsingh** [comment]
Ah no problem, I've only tested the theme in a gui with the Fira Code font. Let me know if its an issue with a certain font

**Comment by aserowy** [comment]
Im also in the fira code club, but i am a fan of light weight. im running semi-light now. The colors are way better that way.
