### ISSUE TITLE
Disable bold style

### ISSUE THREAD

**Issue by Lemesigor** [shaunsingh/nord.nvim#81]
Right now the theme doesn't seems to have the option to disable bold styles in the code. 
<img width="573" alt="Screen Shot 2022-02-10 at 16 30 50" src="https://user-images.githubusercontent.com/51129898/153482657-36e3e3e1-f30f-4e2f-bfde-12e7b511de26.png">

**Comment by freddiehaddad** [comment]
Correct.  As a workaround, you can disable bold fonts for most terminals.  I use iTerm2 and in the preferences I can disable bold fonts which makes implicitly disables it in neovim even if bold is set to enabled.

**Comment by ikovac** [comment]
Any updates on this one? I am using Kitty and according to https://github.com/kovidgoyal/kitty/issues/135 I am unable to turn off bold fonts in my terminal. Is there any way to turn off bold fonts for nord theme?

**Comment by shaunsingh** [comment]
Sorry for the long delay, I'll push the fix (along with a revamp of the theme) soon

**Comment by austinwhite** [comment]
Any ETA on when this fix will be pushed?

**Comment by shaunsingh** [comment]
working on a rewrite which will include a fix, eta about a few days or so

**Comment by Lemesigor** [comment]
Issue fixed in https://github.com/shaunsingh/nord.nvim/pull/118

**Comment by michaelfresco** [comment]
> Any updates on this one? I am using Kitty and according to [kovidgoyal/kitty#135](https://github.com/kovidgoyal/kitty/issues/135) I am unable to turn off bold fonts in my terminal. Is there any way to turn off bold fonts for nord theme?

Maybe use iTerm2 instead?
