### ISSUE TITLE
I just want to ask whether you mind to share your configuration of lualine showing in the picture of nord theme or not.

### ISSUE THREAD

**Issue by LeoGitHuber** [shaunsingh/nord.nvim#88]
Your Nord theme is wonderful. The lualine showing the picture looks really pretty. I'm sorry to bother you for that.

**Comment by Ruixi-rebirth** [comment]
> Your Nord theme is wonderful. The lualine showing the picture looks really pretty. I'm sorry to bother you for that.

**Did you get his configuration? Can you share?**

**Comment by LeoGitHuber** [comment]
> > Your Nord theme is wonderful. The lualine showing the picture looks really pretty. I'm sorry to bother you for that.
> 
> **Did you get his configuration? Can you share?**

Sorry, I didn't get the configuration.
