### ISSUE TITLE
IncSearch bg color

### ISSUE THREAD

**Issue by pehweihang** [shaunsingh/nord.nvim#89]
When searching and replace with confirmation, its impossible to see the current selection.

![image_2022-03-26_23-19-28](https://user-images.githubusercontent.com/25743314/160245978-853c720d-729c-4ff9-8fb9-8424317e290e.png)

**Comment by powelleric** [comment]
This is an issue for me too.  Has anyone found a resolution for this?  It is a dealbreaker for me

**Comment by antoineco** [comment]
@shaunsingh I believe this can now be closed?
